#!/usr/bin/env sh
. "$(dirname "$0")/common.sh"

# If any .po files are staged, recompile and re-stage the compiled catalogs
if git diff --cached --name-only | grep -q '\.po$'; then
  yarn lingui compile
  git add src/i18n/locales/compiled/
fi
