name: Build and Deploy to App Stores (prd)

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'app.config.ts'
      - 'eas.json'
      - 'google-services-prd.json'
      - 'GoogleService-Info-prd.plist'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform'
        required: true
        type: choice
        options:
          - all
          - ios
          - android

jobs:
  deploy:
    uses: ./.github/workflows/expo-store-deploy.yml
    secrets: inherit
    with:
      environment: prd
      platform: ${{ github.event_name == 'push' && 'all' || inputs.platform }}
